/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.36c.                          *
*        Compiled Sep 23 2016, 09:03:11                              *
*                                                                    *
*        (c) 1998 - 2016 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: ambiq_logo                                            *
* Dimensions:  240 * 58                                              *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/
#ifndef __NEZA1_H__
#define __NEZA1_H__

#include "am_mcu_apollo.h"
#include "am_bsp.h"
#include "am_util.h"

#include <stdlib.h>
//240 * 58
//const unsigned short _acambiq_logo[];
extern const uint8_t gImage_NeZa1[];

/*************************** End of file ****************************/

#endif  //__NEZA1_H__
