/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#ifndef PB_CALLING_PB_H_INCLUDED
#define PB_CALLING_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ForwardATCommand {
    char command[34];
/* @@protoc_insertion_point(struct:ForwardATCommand) */
} ForwardATCommand;

typedef struct _IncomingCall {
    char caller_number[34];
/* @@protoc_insertion_point(struct:IncomingCall) */
} IncomingCall;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ForwardATCommand_init_default            {""}
#define IncomingCall_init_default                {""}
#define ForwardATCommand_init_zero               {""}
#define IncomingCall_init_zero                   {""}

/* Field tags (for use in manual encoding/decoding) */
#define ForwardATCommand_command_tag             1
#define IncomingCall_caller_number_tag           1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ForwardATCommand_fields[2];
extern const pb_field_t IncomingCall_fields[2];

/* Maximum encoded size of messages (where known) */
#define ForwardATCommand_size                    36
#define IncomingCall_size                        36

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CALLING_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
