/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#ifndef PB_CENTRAL_PB_H_INCLUDED
#define PB_CENTRAL_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Platform {
    Platform_UNDEFINED = 0,
    Platform_IOS = 1,
    Platform_ANDROID = 2
} Platform;
#define _Platform_MIN Platform_UNDEFINED
#define _Platform_MAX Platform_ANDROID
#define _Platform_ARRAYSIZE ((Platform)(Platform_ANDROID+1))

/* Struct definitions */
typedef struct _GetCentralInformation {
    char dummy_field;
/* @@protoc_insertion_point(struct:GetCentralInformation) */
} GetCentralInformation;

typedef struct _CentralInformation {
    char name[32];
    Platform platform;
/* @@protoc_insertion_point(struct:CentralInformation) */
} CentralInformation;

/* Default values for struct fields */

/* Initializer values for message structs */
#define CentralInformation_init_default          {"", _Platform_MIN}
#define GetCentralInformation_init_default       {0}
#define CentralInformation_init_zero             {"", _Platform_MIN}
#define GetCentralInformation_init_zero          {0}

/* Field tags (for use in manual encoding/decoding) */
#define CentralInformation_name_tag              1
#define CentralInformation_platform_tag          2

/* Struct field encoding specification for nanopb */
extern const pb_field_t CentralInformation_fields[3];
extern const pb_field_t GetCentralInformation_fields[1];

/* Maximum encoded size of messages (where known) */
#define CentralInformation_size                  36
#define GetCentralInformation_size               0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CENTRAL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
