/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#ifndef PB_SYSTEM_PB_H_INCLUDED
#define PB_SYSTEM_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _KeepAlive {
    char dummy_field;
/* @@protoc_insertion_point(struct:KeepAlive) */
} KeepAlive;

typedef struct _RemoveDevice {
    char dummy_field;
/* @@protoc_insertion_point(struct:RemoveDevice) */
} RemoveDevice;

typedef struct _ResetConnection {
    uint32_t timeout;
    bool force_disconnect;
/* @@protoc_insertion_point(struct:ResetConnection) */
} ResetConnection;

typedef struct _SynchronizeSettings {
    uint32_t timestamp_hi;
    uint32_t timestamp_lo;
/* @@protoc_insertion_point(struct:SynchronizeSettings) */
} SynchronizeSettings;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ResetConnection_init_default             {0, 0}
#define SynchronizeSettings_init_default         {0, 0}
#define KeepAlive_init_default                   {0}
#define RemoveDevice_init_default                {0}
#define ResetConnection_init_zero                {0, 0}
#define SynchronizeSettings_init_zero            {0, 0}
#define KeepAlive_init_zero                      {0}
#define RemoveDevice_init_zero                   {0}

/* Field tags (for use in manual encoding/decoding) */
#define ResetConnection_timeout_tag              1
#define ResetConnection_force_disconnect_tag     2
#define SynchronizeSettings_timestamp_hi_tag     1
#define SynchronizeSettings_timestamp_lo_tag     2

/* Struct field encoding specification for nanopb */
extern const pb_field_t ResetConnection_fields[3];
extern const pb_field_t SynchronizeSettings_fields[3];
extern const pb_field_t KeepAlive_fields[1];
extern const pb_field_t RemoveDevice_fields[1];

/* Maximum encoded size of messages (where known) */
#define ResetConnection_size                     8
#define SynchronizeSettings_size                 12
#define KeepAlive_size                           0
#define RemoveDevice_size                        0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SYSTEM_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
