/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#ifndef PB_TRANSPORT_PB_H_INCLUDED
#define PB_TRANSPORT_PB_H_INCLUDED
#include <pb.h>

#include "common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) ConnectionDetails_identifier_t;
typedef struct _ConnectionDetails {
    ConnectionDetails_identifier_t identifier;
/* @@protoc_insertion_point(struct:ConnectionDetails) */
} ConnectionDetails;

typedef struct _SwitchTransport {
    Transport new_transport;
/* @@protoc_insertion_point(struct:SwitchTransport) */
} SwitchTransport;

typedef struct _UpgradeTransport {
    Transport transport;
/* @@protoc_insertion_point(struct:UpgradeTransport) */
} UpgradeTransport;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ConnectionDetails_init_default           {{0, {0}}}
#define UpgradeTransport_init_default            {_Transport_MIN}
#define SwitchTransport_init_default             {_Transport_MIN}
#define ConnectionDetails_init_zero              {{0, {0}}}
#define UpgradeTransport_init_zero               {_Transport_MIN}
#define SwitchTransport_init_zero                {_Transport_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define ConnectionDetails_identifier_tag         1
#define SwitchTransport_new_transport_tag        1
#define UpgradeTransport_transport_tag           1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ConnectionDetails_fields[2];
extern const pb_field_t UpgradeTransport_fields[2];
extern const pb_field_t SwitchTransport_fields[2];

/* Maximum encoded size of messages (where known) */
#define ConnectionDetails_size                   66
#define UpgradeTransport_size                    2
#define SwitchTransport_size                     2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TRANSPORT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
